Fixing the build issue
fix:  for the build issue "AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

"cryptography 39.0.0 no longer supports openssl 1.1.0 or older and thus is causing this issue.
Reference:

pyca/cryptography#7959
https://cryptography.io/en/latest/changelog/#v39-0-0
As a workaround until the dependencies are fixed, you can force install cryptography 38.0.4 and sam should work (I just verified with my CI/CD builds which all got broken today due to the cryptography update).